# -*- coding: utf-8 -*- noqa
"""
Created on Sun Apr 20 23:09:12 2025

@author: Joel Tapia Salvador
"""
import environment

models = {
    'decision_tree_classifier': environment.sklearn.tree.DecisionTreeClassifier,
    'decision_tree_regressor': environment.sklearn.tree.DecisionTreeRegressor,
    'random_forest_classifier': environment.sklearn.ensemble.RandomForestClassifier,
    'random_forest_regressor': environment.sklearn.ensemble.RandomForestRegressor,
    'linear_regression': environment.sklearn.linear_model.LinearRegression,
}

parameters = {
    'decision_tree_classifier': [
        {
            'criterion': 'gini',
            'splitter': 'best',
            'max_depth': None,
            'min_samples_split': 2,
            'min_samples_leaf': 1,
            'min_weight_fraction_leaf': 0.0,
            'max_features': None,
            'random_state': environment.SEED,
            'max_leaf_nodes': None,
            'min_impurity_decrease': 0.0,
            'class_weight': None,
            'ccp_alpha': 0.0,
        },
    ],
    'decision_tree_regressor': [
        {
            'criterion': 'squared_error',
            'splitter': 'best',
            'max_depth': None,
            'min_samples_split': 2,
            'min_samples_leaf': 1,
            'min_weight_fraction_leaf': 0.0,
            'max_features': None,
            'random_state': environment.SEED,
            'max_leaf_nodes': None,
            'min_impurity_decrease': 0.0,
            'ccp_alpha': 0.0,
        },
    ],
    'random_forest_classifier': [
        {
            'n_estimators': 100,
            'criterion': 'gini',
            'max_depth': None,
            'min_samples_split': 2,
            'min_samples_leaf': 1,
            'min_weight_fraction_leaf': 0.0,
            'max_features': 'sqrt',
            'max_leaf_nodes': None,
            'min_impurity_decrease': 0.0,
            'bootstrap': True,
            'oob_score': False,
            'n_jobs': None,
            'random_state': environment.SEED,
            'verbose': 0,
            'warm_start': False,
            'class_weight': None,
            'ccp_alpha': 0.0,
            'max_samples': None,
        },
        {
            'n_estimators': 100,
            'criterion': 'gini',
            'max_depth': None,
            'min_samples_split': 2,
            'min_samples_leaf': 1,
            'min_weight_fraction_leaf': 0.0,
            'max_features': 'sqrt',
            'max_leaf_nodes': None,
            'min_impurity_decrease': 0.0,
            'bootstrap': False,
            'oob_score': False,
            'n_jobs': None,
            'random_state': environment.SEED,
            'verbose': 0,
            'warm_start': False,
            'class_weight': None,
            'ccp_alpha': 0.0,
            'max_samples': None,
        },
        {
            'n_estimators': 300,
            'criterion': 'gini',
            'max_depth': None,
            'min_samples_split': 2,
            'min_samples_leaf': 1,
            'min_weight_fraction_leaf': 0.0,
            'max_features': 'sqrt',
            'max_leaf_nodes': None,
            'min_impurity_decrease': 0.0,
            'bootstrap': True,
            'oob_score': False,
            'n_jobs': None,
            'random_state': environment.SEED,
            'verbose': 0,
            'warm_start': False,
            'class_weight': None,
            'ccp_alpha': 0.0,
            'max_samples': None,
        },
        {
            'n_estimators': 300,
            'criterion': 'gini',
            'max_depth': None,
            'min_samples_split': 2,
            'min_samples_leaf': 1,
            'min_weight_fraction_leaf': 0.0,
            'max_features': 'sqrt',
            'max_leaf_nodes': None,
            'min_impurity_decrease': 0.0,
            'bootstrap': False,
            'oob_score': False,
            'n_jobs': None,
            'random_state': environment.SEED,
            'verbose': 0,
            'warm_start': False,
            'class_weight': None,
            'ccp_alpha': 0.0,
            'max_samples': None,
        },
    ],
    'random_forest_regressor': [
        {
            'n_estimators': 100,
            'criterion': 'squared_error',
            'max_depth': None,
            'min_samples_split': 2,
            'min_samples_leaf': 1,
            'min_weight_fraction_leaf': 0.0,
            'max_features': 1.0,
            'max_leaf_nodes': None,
            'min_impurity_decrease': 0.0,
            'bootstrap': True,
            'oob_score': False,
            'n_jobs': None,
            'random_state': environment.SEED,
            'verbose': 0,
            'warm_start': False,
            'ccp_alpha': 0.0,
            'max_samples': None,
        },
        {
            'n_estimators': 100,
            'criterion': 'squared_error',
            'max_depth': None,
            'min_samples_split': 2,
            'min_samples_leaf': 1,
            'min_weight_fraction_leaf': 0.0,
            'max_features': 1.0,
            'max_leaf_nodes': None,
            'min_impurity_decrease': 0.0,
            'bootstrap': False,
            'oob_score': False,
            'n_jobs': None,
            'random_state': environment.SEED,
            'verbose': 0,
            'warm_start': False,
            'ccp_alpha': 0.0,
            'max_samples': None,
        },
        {
            'n_estimators': 300,
            'criterion': 'squared_error',
            'max_depth': None,
            'min_samples_split': 2,
            'min_samples_leaf': 1,
            'min_weight_fraction_leaf': 0.0,
            'max_features': 1.0,
            'max_leaf_nodes': None,
            'min_impurity_decrease': 0.0,
            'bootstrap': True,
            'oob_score': False,
            'n_jobs': None,
            'random_state': environment.SEED,
            'verbose': 0,
            'warm_start': False,
            'ccp_alpha': 0.0,
            'max_samples': None,
        },
        {
            'n_estimators': 300,
            'criterion': 'squared_error',
            'max_depth': None,
            'min_samples_split': 2,
            'min_samples_leaf': 1,
            'min_weight_fraction_leaf': 0.0,
            'max_features': 1.0,
            'max_leaf_nodes': None,
            'min_impurity_decrease': 0.0,
            'bootstrap': False,
            'oob_score': False,
            'n_jobs': None,
            'random_state': environment.SEED,
            'verbose': 0,
            'warm_start': False,
            'ccp_alpha': 0.0,
            'max_samples': None,
        },
    ],
    'linear_regression': [
        {
            'fit_intercept': True,
            'copy_X': True,
            'n_jobs': None,
            'positive': False,
        },
    ],
}
