name: TFG
channels:
  - pytorch
  - nvidia
  - michael_wild
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - ca-certificates=2025.1.31
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - cloudpickle=3.1.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.1.1
  - cuda-cccl=12.8.90
  - cuda-cccl_win-64=12.8.90
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.8.90
  - cuda-opencl-dev=12.8.90
  - cuda-profiler-api=12.8.90
  - cuda-runtime=12.4.1
  - cuda-version=12.8
  - cycler=0.12.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - executing=2.1.0
  - filelock=3.16.1
  - fonttools=4.53.1
  - freetype=2.13.3
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=69.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - intel-openmp=2025.0.4
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.15
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.3.9.90
  - libcurand-dev=10.3.9.90
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.17
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=12.8.90
  - libnvfatbin-dev=12.8.90
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libpng=1.6.47
  - libsodium=1.0.18
  - libsqlite=3.49.1
  - libtiff=4.5.0
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.13
  - libxml2=2.13.6
  - libzlib=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.5
  - matplotlib=3.7.3
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - networkx=3.1
  - numpy=1.24.4
  - opencl-headers=2024.10.24
  - openjpeg=2.5.0
  - openssl=1.1.1w
  - packaging=24.2
  - pandas=2.0.3
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=20.0.2
  - platformdirs=4.3.6
  - pooch=1.8.2
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.1.4
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.8
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2024.2
  - pywin32=306
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt=5.12.9
  - requests=2.32.3
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - setuptools=75.3.0
  - six=1.16.0
  - spyder-kernels=3.0.3
  - sqlite=3.49.1
  - stack_data=0.6.2
  - sympy=1.13.3
  - tbb=2021.13.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.13
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - torchaudio==2.4.1
      - torchvision==0.19.1
