name: TFG
channels:
  - pytorch
  - nvidia
  - michael_wild
  - conda-forge
  - defaults
dependencies:
  - flask=3.0.3
  - matplotlib=3.7.3
  - numpy=1.24.4
  - pandas=2.0.3
  - psutil=6.0.0
  - python=3.8.10
  - pytorch=2.4.1
  - scikit-learn=1.3.2
  - pip:
      - torchaudio==2.4.1
      - torchvision==0.19.1
